

FROM php:7.3-apache
RUN docker-php-ext-install pdo pdo_mysql mysqli && docker-php-ext-enable pdo_mysql mysqli


# FROM nginx:stable-alpine
# ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf
# RUN mkdir -p /var/www/html

