

FROM php:8.0.0-fpm-alpine
RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo_mysql


# FROM nginx:stable-alpine
# ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf
# RUN mkdir -p /var/www/html

