version: '3.9'

# networks:
#   laravel:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./job-board:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    # networks:
    #   - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    tty: true
    environment:
      # DB_CONNECTION=mysql
      # DB_HOST=eu-cdbr-west-01.cleardb.com
      # DB_PORT=3306
      # DB_DATABASE=heroku_7df5c5bfe89be30
      # DB_USERNAME=b00618a90c4987
      # DB_PASSWORD=539632ae

      MYSQL_DATABASE: heroku_7df5c5bfe89be30
      MYSQL_USER: b00618a90c4987
      MYSQL_PASSWORD: 539632ae
      MYSQL_ROOT_PASSWORD: secret
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
      
      # MYSQL_DATABASE: tolobase
      # MYSQL_USER: tolobase
      # MYSQL_PASSWORD: secret
      # MYSQL_ROOT_PASSWORD: secret
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    volumes: 
      - ./mysql:/var/lib/mysql
    # networks:
    #   - laravel
   
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./job-board:/var/www/html:delegated
    # ports:
    #     - "9000:9000"
    # networks:
    #   - laravel


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./job-board:/var/www/html
    working_dir: /var/www/html
    # networks:
    #   - laravel


  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    volumes:
      - ./job-board:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html

  npm:
    image: node:13.7
    container_name: npm
    entrypoint: ['npm']
    ports:
      - 3000:3000
    volumes:
      - ./job-board:/var/www/html
    working_dir: /var/www/html
    # networks:
    #   - laravel