version: '3.9'

# networks:
#   laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./job-board:/var/www/html:delegated ############################
    depends_on:
      - php
      - mysql
    # networks:
    #   - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    tty: true
    environment:
      MYSQL_DATABASE: tolobase
      MYSQL_USER: tolobase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./mysql:/var/lib/mysql
    # networks:
    #   - laravel
   
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./job-board:/var/www/html:delegated
    # ports:
    #     - "9000:9000"
    # networks:
    #   - laravel


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./job-board:/var/www/html
    # working_dir: /var/www/html
    # networks:
    #   - laravel


  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    volumes:
      - ./job-board:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html

  npm:
    image: node:13.7
    container_name: npm
    entrypoint: ['npm']
    # command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    volumes:
      - ./job-board:/var/www/html
    working_dir: /var/www/html
    # networks:
    #   - laravel