version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 5d977e4aab32bb030d2aee43c1b0a949027450360e0ef83a788cc0958b47bf74
      POSTGRES_DB: laravel_docker
    volumes:
      - ./postgres:/var/lib/postgres
    ports:
      - '5432:5432'

  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: ./php/php.dockerfile
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database