version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./social-login:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 17a85725458036daf13ea9e136974cf72c23251dab80ec028814c2be7577eb0a
      POSTGRES_DB: d99k5c35cdejdf
    volumes:
      - ./postgres:/var/lib/postgres
    ports:
      - 5432:5432

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./social-login:/var/www/html

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./social-login:/var/www/html
    working_dir: /var/www/html


  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    volumes:
      - ./social-login:/var/www/html
    depends_on:
      - database
    working_dir: /var/www/html

  npm:
    image: node:13.7
    container_name: npm
    entrypoint: ['npm']
    ports:
      - 3000:3000
    volumes:
      - ./social-login:/var/www/html
    working_dir: /var/www/html

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: mailhog
  #   ports:
  #     - 8025:8025