version: "3.9"

volumes:
  datafile:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Property:/var/www/html:delegated
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - DB_HOSTNAME=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DATABASE=property
    volumes:
      - datafile:/var/lib/mysql
    restart: always

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./Property:/var/www/html:delegated

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  # website:
  #   container_name: php73
  #   build:
  #     context: .
  #     dockerfile: php.dockerfile
  #   environment:
  #     - MYSQL_DBHOST=mysql
  #     - MYSQL_DBUSER=root
  #     - MYSQL_DBPASS=secret
  #     - MYSQL_DBNAME=propertydb
  #   ports:
  #     - 8080:80
  #     - 8083:443
  #   depends_on:
  #     - mysql
