version: "3.8"

volumes:
  datafiles:

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      - MYSQL_DBNAME=propertydb
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql
