version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 99bf4eada86ad0c942fc16fe7044866e604ab6eb7c213f0f13a515cb524f23c3
      POSTGRES_DB: d17bbsnpfmf7ft
    volumes:
      - ./postgres:/var/lib/postgres
    ports:
      - 5432:5432

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html

 
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

    