version: '3.9'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./jetstream-test:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: 5d977e4aab32bb030d2aee43c1b0a949027450360e0ef83a788cc0958b47bf74
      POSTGRES_DB: d8b4rsqoj1rl7l
    volumes:
      - ./postgres:/var/lib/postgres
    ports:
      - 5432:5432

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./jetstream-test:/var/www/html

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./jetstream-test:/var/www/html
    working_dir: /var/www/html


  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    volumes:
      - ./jetstream-test:/var/www/html
    depends_on:
      - database
    working_dir: /var/www/html

  npm:
    image: node:13.7
    container_name: npm
    entrypoint: ['npm']
    ports:
      - 3000:3000
    volumes:
      - ./jetstream-test:/var/www/html
    working_dir: /var/www/html

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025